pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "dev.architectury.loom") {
                useModule("dev.architectury:architectury-loom:${requested.version}")
            }
        }
    }
    repositories {
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases/" }
        maven { url = "https://maven.fabricmc.net/" }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "oneironaut-neoforge"
